routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//User

Route::get('/', 'HomeController@index')->name('home');

Route::get('/test','HomeController@test');


//Admin
Route::prefix('admin')
    ->namespace('Admin')->middleware(['auth'])
    ->group(function () {
        Route::get('/', 'AdminController@index')->name('dashboard');

        Route::resource("product", "ProductController");

        Route::resource("topping", "ToppingController");

        Route::resource("category", "CategoryController");

        Route::resource("price", "PriceController");
    });

Auth::routes(['register' => false, 'reset' => false]);


// Route::get('/home', 'HomeController@index')->name('home');

app/Price.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Price extends Model
{
    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}

app/Http/Controllers/Admin/PriceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Price;
use App\Product;
use Illuminate\Http\Request;

use function GuzzleHttp\Promise\all;

class PriceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data['prices'] = Price::all();
        

        $price = Price::all();
        // $harga = Price::all()->count();
        // // return $harga;

        // for ($x = 1; $x <= $harga; $x++) {

        //     $price[$x] = Price::find($x);
        // }
        return view('pages.admin.price.index', ['price' => $price]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['category'] = Category::all();

        $data['product'] = Category::join('products', 'products.category_id', 'categories.id')
            ->select('products.*')->get();



        return view('pages.admin.price.create', $data);

        // $data['products'] = Product::all();

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'drink', 'drink_price' => 'required',
        ]);

        $price = new Price();
        $price->product_id = $request->drink;
        $price->type = $request->type;
        $price->size = $request->size;
        $price->price = $request->drink_price;

        // return $price;


        $price->save();
        alert()->success('Sukses !', 'Harga Ditambahkan.');
        return redirect()->route('price.create');

        // $data['product'] = Category::join('products', 'products.category_id', 'categories.id')
        //     ->select('products.*')->get();

        // return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Category::join('products', 'products.category_id', 'categories.id')
            ->select('products.*')->where('products.category_id', $id)->get();

        echo json_encode($data);



        // echo $id;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {


        $item = Price::findOrFail($id);
        return view(
            'pages.admin.price.edit',
            [
                'item' => $item
            ],

        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Price::where('id', $id)
            ->update([
                'type' => $request->type,
                'size' => $request->size,
                'price' => $request->drink_price
            ]);

        alert()->success('Sukses !', 'Minuman Berhasil diubah.');
        return redirect()->route('price.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $product = Product::find($request->id);
        // $product->price()->where('product_id',17);

        $price = Price::find($id);

        // // $price->product()->where('product_id', 17);
        $price->delete();
        alert()->success('Sukses !', 'Harga Berhasil dihapus.');
        return redirect()->route('price.index');
        // return $id;

        // dd($request->id);
    }







    public function cariminuman()
    {
        $data = Category::join('products', 'products.category_id', 'categories.id')
            ->select('products.*')->get();

        // return $data;
        echo "hello ";
        // return response()->json([
        //     'success' => true,
        //     'message' => 'List Data admin',
        //     'data'    => $data
        // ], 200);
    }
}

resources/views/pages/admin/price/create.blade.php
@extends('layouts.admin')

@section('active')

<li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
</li>

<li class="nav-item ">
    <a class="nav-link" href="{{ route('product.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Minuman</span></a>
</li>

<li class="nav-item ">
    <a class="nav-link" href="{{ route('topping.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Topping</span></a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{{ route('category.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Kategori</span>
    </a>
</li>

<li class="nav-item active">
    <a class="nav-link" href="{{ route('price.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Harga</span>
    </a>
</li>

@endsection

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Harga Minuman</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('category.index') }}">Harga</a></li>
                <li class="breadcrumb-item active" aria-current="page">Tambah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Form Tambah Harga Minuman</h6>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal" action="{{route('price.store')}}" method="POST">
                        @csrf
                        <div class="row">


                            <div class="form-group col-md-6">
                                <label for="category">Kategori</label>
                                <select class="form-control" id="category" name="category" onchange="changeFunc();">
                                    <option value="">-- Pilih Kategori --</option>
                                    @foreach ($category as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group col-md-6">
                                <label for="category">Minuman</label>
                                <div id="drinks">
                                    <select class="form-control" id="drink" name="drink" disabled>
                                        <option value="">-- Pilih Minuman --</option>
                                    </select>
                                </div>
                                <!-- <select class="form-control" id="drink" name="drink">
                                    <option value="">-- Pilih Minuman --</option>
                                    @foreach ($product as $item)
                                    @php

                                    @endphp
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                                </select> -->
                            </div>

                            <div class="form-group col-md-6">
                                <label for="category">Type (Optional)</label>
                                <select class="form-control" id="type" name="type">
                                    <option value="">-- Pilih Tipe --</option>
                                    <option value="1">Hot</option>
                                    <option value="2">Ice</option>
                                </select>
                            </div>

                            <div class="form-group col-md-6">
                                <label for="category">Size (Optional) </label>
                                <select class="form-control" id="size" name="size">
                                    <option value="">-- Pilih Size --</option>
                                    <option value="1">Reguler</option>
                                    <option value="2">Large</option>
                                </select>
                            </div>


                            <div class="form-group col-md-12">
                                <label for="drink">Harga Minuman</label>
                                <input type="number" class="form-control" id="drink_price" name="drink_price" placeholder="ex : 10000" required>
                                <p id="test1"></p>
                            </div>

                            <button type="submit" class="btn btn-primary col-lg-3 offset-lg-4">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

@section('addScript')
<script type="text/javascript">
    function changeFunc() {
        string = '';
        var s = document.getElementById('category').value;

        var ajax = new XMLHttpRequest();
        var method = "GET";
        var url = '/admin/price/' + s;
        var asynchronous = true;

        ajax.open(method, url, asynchronous);

        ajax.send();

        if (s === '') {
            string = "<select class = 'form-control' id = 'drink' name = 'drink' disabled > <option value = ''> --Pilih Minuman-- </option> </select> "
            document.getElementById('drinks').innerHTML = string;
        }




        ajax.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {

                var data = JSON.parse(this.responseText);
                console.log(data);



                string = "";


                for (z = 0; z < data.length; z++) {
                    // x += data[z].name;
                    string = string + "<option value='" + data[z].id + "'>" + data[z].name + "</option>";
                }

                // var id = [data.id];
                // var name = [date.name];
                // console.log(name);
                // for (i = 0; i < x.length; i++) {

                //     string = string + "<option value='" + id + "'>" + name[i] + "</option>";
                // }
                string = "<select class='form-control' id='drink' name='drink'>" + string + "</select>";

                document.getElementById('drinks').innerHTML = string;



            }



        }









    }
</script>
@endsection

resources/views/pages/admin/price/edit.blade.php
@extends('layouts.admin')

@section('active')

<li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
</li>

<li class="nav-item ">
    <a class="nav-link" href="{{ route('product.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Minuman</span></a>
</li>

<li class="nav-item ">
    <a class="nav-link" href="{{ route('topping.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Topping</span></a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{{ route('category.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Kategori</span>
    </a>
</li>

<li class="nav-item active">
    <a class="nav-link" href="{{ route('price.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Harga</span>
    </a>
</li>

@endsection

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Harga Minuman</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('category.index') }}">Harga</a></li>
                <li class="breadcrumb-item active" aria-current="page">Tambah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Form Ubah Harga Minuman</h6>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal" action="{{route('price.update',$item->id)}}" method="POST">
                        @method('put')
                        @csrf
                        <div class="row">

                            <div class="form-group col-md-12">
                                <label for="category">Minuman</label>
                                <div id="drinks">
                                    <select class="form-control" id="drink" name="drink" disabled>
                                        <option value="">{{$item->product->name}}</option>
                                    </select>
                                </div>
                               
                            </div>

                            <div class="form-group col-md-6">
                                <label for="category">Type (Optional)</label>
                                <select class="form-control" id="type" name="type">
                                    <option value="">-- Pilih Tipe --</option>
                                    <option value="1">Hot</option>
                                    <option value="2">Ice</option>
                                </select>
                            </div>

                            <div class="form-group col-md-6">
                                <label for="category">Size (Optional) </label>
                                <select class="form-control" id="size" name="size">
                                    <option value="">-- Pilih Size --</option>
                                    <option value="1">Reguler</option>
                                    <option value="2">Large</option>
                                </select>
                            </div>


                            <div class="form-group col-md-12">
                                <label for="drink">Harga Minuman</label>
                                <input type="number" class="form-control" id="drink_price" name="drink_price" value="{{$item->price}}" required>
                                <p id="test1"></p>
                            </div>

                            <button type="submit" class="btn btn-primary col-lg-3 offset-lg-4">Ubah</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

@section('addScript')
<script type="text/javascript">
    function changeFunc() {
        string = '';
        var s = document.getElementById('category').value;

        var ajax = new XMLHttpRequest();
        var method = "GET";
        var url = '/admin/price/' + s;
        var asynchronous = true;

        ajax.open(method, url, asynchronous);

        ajax.send();

        if (s === '') {
            string = "<select class = 'form-control' id = 'drink' name = 'drink' disabled > <option value = ''> --Pilih Minuman-- </option> </select> "
            document.getElementById('drinks').innerHTML = string;
        }




        ajax.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {

                var data = JSON.parse(this.responseText);
                console.log(data);



                string = "";


                for (z = 0; z < data.length; z++) {
                    // x += data[z].name;
                    string = string + "<option value='" + data[z].id + "'>" + data[z].name + "</option>";
                }

                // var id = [data.id];
                // var name = [date.name];
                // console.log(name);
                // for (i = 0; i < x.length; i++) {

                //     string = string + "<option value='" + id + "'>" + name[i] + "</option>";
                // }
                string = "<select class='form-control' id='drink' name='drink'>" + string + "</select>";

                document.getElementById('drinks').innerHTML = string;



            }



        }









    }
</script>
@endsection

resources/views/pages/admin/price/index.blade.php
@extends('layouts.admin')

@section('active')

<li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
</li>

<li class="nav-item ">
    <a class="nav-link" href="{{ route('product.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Minuman</span></a>
</li>

<li class="nav-item ">
    <a class="nav-link" href="{{ route('topping.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Topping</span></a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{{ route('category.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Kategori</span>
    </a>
</li>

<li class="nav-item active">
    <a class="nav-link" href="{{ route('price.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Harga</span>
    </a>
</li>

@endsection


@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Daftar Harga Minuman</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Harga</li>
            </ol>
        </nav>
    </div>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{{ route('price.create') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Harga Minuman
        </a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="example" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Type</th>
                            <th>Size</th>
                            <th>Price</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($price as $item)
                        <tr>
                            <td>{{$item->product->name}}</td>
                            <td>{{$item->type}}</td>
                            <td>{{$item->size}}</td>
                            <td>{{$item->price}}</td>


                            <td class="text-center">
                                <div class="btn-group">
                                    <div class="col-md-6 mt-2">

                                        <a href="{{route('price.edit',$item->id)}}" class="btn btn-primary fas fa-edit pr-1" style="color: aliceblue">Ubah</a>

                                    </div>
                                    <div class="col-md-6 mt-2">
                                        <button class="btn btn-danger" data-toggle="modal" data-id="{{ $item->id }}" data-target="#deleteModal">
                                            <i class="fa fa-trash pr-1">Hapus</i>
                                        </button>
                                    </div>

                                    <!-- Delete Modal-->
                                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Hapus Produk</h5>
                                                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">Apakah anda yakin ingin menghapusnya?</div>
                                                <div class="modal-footer">
                                                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button>
                                                    <form action="{{ route('price.destroy',$item->id) }}" method="POST" class="delete">
                                                        @csrf
                                                        @method('delete')
                                                        <input type="hidden" name="id" id="input-id">
                                                        <button class="btn btn-primary btn-delete">Hapus</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection